FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY tsconfig.json ./
COPY jest.config.js ./
COPY .eslintrc.js ./
COPY src ./src
COPY tests ./tests

EXPOSE 3028

CMD ["npm", "run", "dev"]
